import streamlit as st

def clean_session():
    st.session_state["ldv"] = ""
    
    st.session_state["box-01"] = ""
    st.session_state["box-02"] = ""
    st.session_state["box-03"] = ""
    st.session_state["box-04"] = ""
    st.session_state["box-05"] = ""
    st.session_state["box-06"] = ""
    st.session_state["box-10"] = ""
    st.session_state["box-11"] = ""
    st.session_state["box-12"] = ""
    st.session_state["box-13"] = ""
    st.session_state["box-14"] = ""
    st.session_state["box-16"] = ""
    st.session_state["box-16-orario"] = ""
    st.session_state["box-17"] = ""
    st.session_state["box-18"] = ""
    st.session_state["box-19-1"] = ""
    st.session_state["box-19-2"] = ""
    st.session_state["box-23"] = ""
    st.session_state["box-24"] = ""
    st.session_state["box-25"] = ""
    st.session_state["box-29"] = ""
    st.session_state["box-49"] = ""
    st.session_state["box-57"] = ""
    st.session_state["box-62-paese"] = ""
    st.session_state["box-62-stazione"] = ""
    st.session_state["box-62-impresa"] = ""
    st.session_state["box-62-spedizione"] = ""
    
    st.session_state["box-01-clean"] = ""
    st.session_state["box-02-clean"] = ""
    st.session_state["box-03-clean"] = ""
    st.session_state["box-04-clean"] = ""
    st.session_state["box-05-clean"] = ""
    st.session_state["box-06-clean"] = ""
    st.session_state["box-10-clean"] = ""
    st.session_state["box-11-clean"] = ""
    st.session_state["box-12-clean"] = ""
    st.session_state["box-13-clean"] = ""
    st.session_state["box-14-clean"] = ""
    st.session_state["box-16-clean"] = ""
    st.session_state["box-16-orario-clean"] = ""
    st.session_state["box-17-clean"] = ""
    st.session_state["box-18-clean"] = ""
    st.session_state["box-19-1-clean"] = ""
    st.session_state["box-19-2-clean"] = ""
    st.session_state["box-23-clean"] = ""
    st.session_state["box-24-clean"] = ""
    st.session_state["box-25-clean"] = ""
    st.session_state["box-29-clean"] = ""
    st.session_state["box-49-clean"] = ""
    st.session_state["box-57-clean"] = ""
    st.session_state["box-62-paese-clean"] = ""
    st.session_state["box-62-stazione-clean"] = ""
    st.session_state["box-62-impresa-clean"] = ""
    st.session_state["box-62-spedizione-clean"] = ""
    st.session_state["box-62-luogo-clean"] = ""
    st.session_state["box-62-data-clean"] = ""
    
    st.session_state["box-01-orfeus"] = ""
    st.session_state["box-02-orfeus"] = ""
    st.session_state["box-03-orfeus"] = ""
    st.session_state["box-04-orfeus"] = ""
    st.session_state["box-05-orfeus"] = ""
    st.session_state["box-06-orfeus"] = ""
    st.session_state["box-10-orfeus"] = ""
    st.session_state["box-11-orfeus"] = ""
    st.session_state["box-12-orfeus"] = ""
    st.session_state["box-13-orfeus"] = ""
    st.session_state["box-14-orfeus"] = ""
    st.session_state["box-16-orfeus"] = ""
    st.session_state["box-16-orario-orfeus"] = ""
    st.session_state["box-17-orfeus"] = ""
    st.session_state["box-18-orfeus"] = ""
    st.session_state["box-19-1-orfeus"] = ""
    st.session_state["box-19-2-orfeus"] = ""
    st.session_state["box-23-orfeus"] = ""
    st.session_state["box-24-orfeus"] = ""
    st.session_state["box-25-orfeus"] = ""
    st.session_state["box-29-orfeus"] = ""
    st.session_state["box-49-orfeus"] = ""
    st.session_state["box-57-orfeus"] = ""
    st.session_state["box-62-paese-orfeus"] = ""
    st.session_state["box-62-stazione-orfeus"] = ""
    st.session_state["box-62-impresa-orfeus"] = ""
    st.session_state["box-62-spedizione-orfeus"] = ""
    st.session_state["box-62-luogo-orfeus"] = ""
    st.session_state["box-62-data-orfeus"] = ""
    
    st.session_state["codice-mittente-scelto"] = ""
    st.session_state["codice-destinatario-scelto"] = ""
    
    st.session_state["rds"] = ""
    return